### ISSUE TITLE
Getting Exception

### ISSUE THREAD

**Issue by alok0807** [lumenrobot/program-ab#8]
Hi,

Whenever  i am asking a new question i m getting exception?
Could you please help me to resolve exception?

Regards,
Alok

**Comment by ceefour** [comment]
I no longer support program-ab.

Contributors welcome.

**Comment by alok0807** [comment]
Hi,,
okay.. do you have any other program that I can check?

**Comment by cosesano** [comment]
Can you give more details regarding the problems you are experiencing?
 You mentioned "When you ask New question", did you successfully integrated programab into your application before and it worked fine?

**Comment by alok0807** [comment]
Hi Cosesano,

I have integrated the application in my local system. 
Suppose if I ask a new question like " what is NETSIM"? (its just a normal random question). I am getting the below response:

Human: what is NETSim
STATE=what is NETSim:THAT=unknown:TOPIC=unknown
normalized = what is NETSim
Matched: WHAT IS * <THAT> * <TOPIC> * sraix.aiml
--> localIPAddress = 172.16.206.175
Sraix url='https://weannie.pannous.com/api?input=WHAT+IS+NETSim&locale=en_US&timeZone=330&login=test-user&ip=172.16.206.175&botid=0&key=guest&exclude=Dialogues,ChatBot&out=json'
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
Sraix 'WHAT+IS+NETSim' failed
Matched: SRAIXFAILED <THAT> * <TOPIC> * sraix.aiml
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(Unknown Source)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at org.alicebot.ab.utils.NetworkUtils.responseContent(NetworkUtils.java:50)
	at org.alicebot.ab.Sraix.sraixPannous(Sraix.java:111)
	at org.alicebot.ab.Sraix.sraix(Sraix.java:42)
	at org.alicebot.ab.AIMLProcessor.sraix(AIMLProcessor.java:385)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1050)
	at org.alicebot.ab.AIMLProcessor.evalTagContent(AIMLProcessor.java:246)
	at org.alicebot.ab.AIMLProcessor.recursEval(AIMLProcessor.java:1040)
	at org.alicebot.ab.AIMLProcessor.evalTemplate(AIMLProcessor.java:1133)
	at org.alicebot.ab.AIMLProcessor.respond(AIMLProcessor.java:187)
	at org.alicebot.ab.AIMLProcessor.respond(AIMLProcessor.java:162)
	at org.alicebot.ab.Chat.respond(Chat.java:115)
	at org.alicebot.ab.Chat.respond(Chat.java:140)
	at org.alicebot.ab.Chat.multisentenceRespond(Chat.java:165)
	at Main.testChat(Main.java:105)
	at Main.mainFunction(Main.java:60)
	at Main.main(Main.java:36)
writeCertainIFCaegories learnf.aiml size= 0
Robot: Sorry, nothing found in web services.
I'll try asking Google.
<oob><search>what is NETSim</search></oob>
Human: 

SO it would be better if you help me how to figure it out if I ask a new random question?
or else if there is any way that it should responds as some default answers if its a completely new question for Robot?

Thanks in advance.

**Comment by alok0807** [comment]
Hi,

While executing the "Main.java", i am getting the below exception:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
	at org.alicebot.ab.cli.Main.<clinit>(Main.java:38)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
Please help me out as I have to show some sort of demo.
Thanks in advance.

**Comment by ceefour** [comment]
You need to configure slf4j properly, in this case I assume you want to use log4j so you need that.

**Comment by alok0807** [comment]
Hi,

Could you please help me out how to configure sl4j?
I have added the sl4j jar files in the project.
